majors = [
  "Accounting",
  "Actuarial Mathematics",
  "Africana Studies",
  "Africana Studies–English",
  "Anthropology",
  "Applied Developmental Psychology",
  "Applied Mathematics",
  "Architecture",
  "Architectural Studies",
  "Astronomy",
  "Biochemistry",
  "Bioengineering",
  "Biological Sciences",
  "Business Information Systems",
  "CASE Teacher Preparation",
  "Chemical Engineering",
  "Chemistry",
  "Chinese",
  "Civil Engineering",
  "Classics",
  "Communication: Rhet & Comm",
  "Communication Science",
  "Computational Biology",
  "Computer Engineering",
  "Computer Science",
  "Computational Social Science",
  "Data Science",
  "Dental Hygiene",
  "Dietician Nutritionist Program",
  "Digital Narrative and Interactive Design",
  "Ecology and Evolution",
  "Economics",
  "Economics–Statistics",
  "Electrical Engineering",
  "Emergency Medicine",
  "Engineering Science",
  "English Literature",
  "English Writing",
  "Environmental Science",
  "Environmental Studies",
  "Exercise Science",
  "Film and Media Studies",
  "Finance",
  "French",
  "Gender, Sexuality, and Women's Studies",
  "Geology",
  "German",
  "Global Management",
  "Health Informatics",
  "Health Services",
  "Health and Physical Activity",
  "History",
  "History and Philosophy of Science",
  "History of Art & Architecture",
  "Human Resources Management",
  "Industrial Engineering",
  "Information Science",
  "International and Area Studies",
  "International Studies Co-Major",
  "Italian",
  "Italian Studies",
  "Japanese",
  "Law, Criminal Justice, and Society",
  "Linguistics",
  "Marketing",
  "Materials Science and Engineering",
  "Mathematics",
  "Mathematical Biology",
  "Mathematics-Economics",
  "Mechanical Engineering",
  "Media and Professional Communications",
  "Microbiology",
  "Molecular Biology",
  "Museum Studies",
  "Music",
  "Natural Sciences",
  "Neuroscience",
  "Nursing",
  "Nutrition Science",
  "Pharmacy",
  "Philosophy",
  "Physics",
  "Physics and Astronomy",
  "Physics and Quantum Computing",
  "Political Science",
  "Politics and Philosophy",
  "Psychology"
]

interests = [
  "Artificial Intelligence",
  "Digital Marketing",
  "Renewable Energy",
  "Data Analysis",
  "Creative Writing",
  "Web Development",
  "Graphic Design",
  "Sustainable Agriculture",
  "Blockchain Technology",
  "Music Production",
  "Cyber Security",
  "Virtual Reality",
  "Game Development",
  "Machine Learning",
  "Photography",
  "Mobile App Development",
  "Environmental Conservation",
  "Video Editing",
  "Financial Planning",
  "Public Speaking",
  "Fitness Training",
  "Ethical Hacking",
  "Social Media Strategy",
  "User Experience Design",
  "3D Modeling",
  "Artificial Neural Networks",
  "Cloud Computing",
  "Renewable Resources",
  "Animation Design",
  "Digital Illustration",
  "Augmented Reality",
  "E-Commerce Business",
  "Space Exploration",
  "Human-Computer Interaction",
  "Urban Planning",
  "Robotics Engineering",
  "Quantum Computing",
  "Nanotechnology Research",
  "Organic Chemistry",
  "Astrophysics",
  "Cultural Anthropology",
  "Behavioral Psychology",
  "Forensic Science",
  "Marine Biology",
  "Wildlife Photography",
  "Astrobiology",
  "Political Campaigns",
  "Investment Strategies",
  "Entrepreneurial Ventures",
  "Social Justice",
  "Econometric Modeling",
  "Interior Design",
  "Film Directing",
  "Nonprofit Management",
  "Product Management",
  "Supply Chain Management",
  "Nutritional Science",
  "Criminal Justice Reform",
  "Healthcare Innovation",
  "Sociocultural Studies",
  "Cognitive Science",
  "Global Health",
  "Bioinformatics",
  "Climate Change Policy",
  "Public Health Administration",
  "Corporate Social Responsibility",
  "Epidemiology Research",
  "Artificial Ecosystems",
  "Sports Analytics",
  "Food Sustainability",
  "Fashion Design",
  "Automotive Engineering",
  "Culinary Arts",
  "Digital Entrepreneurship",
  "User Interface Design",
  "Virtual Collaboration",
  "Audio Engineering",
  "Behavioral Economics",
  "Global Trade",
  "Sustainable Urbanization",
  "Renewable Energy Systems",
  "Green Architecture",
  "Media Production",
  "Bioengineering",
  "Space Tourism",
  "Water Resource Management",
  "Telemedicine",
  "Paleontology",
  "Wildlife Conservation",
  "Microfinance",
  "Oceanography",
  "Artificial Intelligence Ethics",
  "Biometric Authentication",
  "Language Translation",
  "Humanitarian Aid",
  "Crisis Management",
  "Educational Technology",
  "Mental Health Advocacy",
  "User Testing",
  "Sports Medicine",
  "Innovation Consulting",
  "Sustainable Fashion",
  "Documentary Filmmaking",
  "Organic Farming"
]